### ISSUE TITLE
alt-3 is the # symbol on a UK keyboard

### ISSUE THREAD

**Issue by far-blue** [merrickp/JumpMarks#2]
Hello :)

Can you possibly make the keyboard shortcuts configurable or possibly just exclude certain ones because while I love this plugin it prevents me typing # because on a UK keyboard # is mapped to alt-3.

**Comment by merrickp** [comment]
Hi there,
I can make a custom configuration screen to define the shortcuts. The advantage of using this plugin is using minimal keystrokes, but most common ones like ([Command + #]) are already taken so I have to make a compromise and use one that say I personally do not use. Is there a combination that works in your UK usage? I am thinking of making a screen that exposes all the control keys with checkboxes.

**Comment by far-blue** [comment]
I think in general it's a good set of keystrokes. It's just the odd one such as alt-3 (#) and alt-2 (€) on the uk keyboard that are a problem. I'd suggest either giving the ability to disable selected keys (i.e. allowing a uk user to disable alt-3 but still keep all the other bookmark numbers) or maybe allowing control over the shortcut keys from the normal Xcode key combination preferences.

**Comment by AliMunchkin** [comment]
Had been wondering why my Macbook Air hash key wasn't working in Xcode over the last few days - finally just realised it was due to this, took a bit of tracking down! 

Just providing this as some constructive feedback - great plugin :)

**Comment by merrickp** [comment]
Thanks for the feedback! I've just created a branch key_remap to track work on this front.
